---
title: "UV Forecast Map"
output: html_notebook
---

```{r}

```

# libraries
```{r}
library(rgdal) # to import maps
library(leaflet) # to make maps
library(htmlwidgets) # to convert to something that can be used in html
library(XML) # for converting XML file to data frame
library(xml2) # for downloading the xml file before parsing
library(tidyverse) # transform and transpose dataframe
```

# import australia map
```{r}
aus_map <- readOGR( 
      dsn= paste0(getwd(),"/data/") , 
      layer="STE_2021_AUST_GDA2020"
    )
```

# import data
```{r}
# uv updating data
uv_link <- "https://uvdata.arpansa.gov.au/xml/uvvalues.xml"
uv_xml <- download_xml(uv_link)
uv_parsed <- xmlParse(uv_xml, useInternalNodes = FALSE)
#uv_data <- xmlToDataFrame(uv_parsed)
uv_list <- xmlToList(uv_parsed)
```

# tranform and transpose the list
```{r}
uv_data <- as.data.frame(t(uv_list))
# remove rownmaes
rownames(uv_data) <- NULL
# edit colnames
colnames(uv_data)[8] <- "fullname"
# convert data types to their proper ones
uv_data <- type.convert(uv_data, as.is = TRUE)
# filter status by "ok"
data <- filter(uv_data, status == "ok") %>%
  select(., -status)
# unlist
data <- as.data.frame(lapply(data, unlist))
```

# get city data list
```{r}
# import file
cities <- read_csv("worldcities.csv")
# filter by australia and choose relevant columns
aus_city <- filter(cities, country == "Australia") %>% 
  select('fullname' = 'city', 'state' = "admin_name", 'lat', 'lng')
```

# merge and get final result
```{r}
# merge data
uvs <- merge(data, aus_city, by = 'fullname', all.x = TRUE) %>%
  na.omit()

```



# test
```{r}
m <- leaflet(data.frame(lat = 55.71654, lng = 12.47484))
m <-  addCircles(m, popup = "testpopup")
m <-  addTiles(m)
m

saveWidget(m, file="testmap.html", selfcontained = TRUE)
```



